{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B70089EA20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pymysql/\n",
      "WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B7009F7140>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pymysql/\n",
      "WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B7009F7BF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pymysql/\n",
      "WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B7009F7E00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pymysql/\n",
      "WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000002B7009F7F50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/pymysql/\n",
      "ERROR: Could not find a version that satisfies the requirement pymysql (from versions: none)\n",
      "ERROR: No matching distribution found for pymysql\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D9F40AEA50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cryptography/\n",
      "WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D9F263B260>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cryptography/\n",
      "WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D9F40F7920>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cryptography/\n",
      "WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D9F40F7B30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cryptography/\n",
      "WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001D9F40F7D40>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/cryptography/\n",
      "ERROR: Could not find a version that satisfies the requirement cryptography (from versions: none)\n",
      "ERROR: No matching distribution found for cryptography\n"
     ]
    },
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pymysql'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-2-4a138818c48d>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[0mget_ipython\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msystem\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'python3 -m pip install cryptography'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[1;32mimport\u001b[0m \u001b[0mpymysql\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[0mtimeout\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m10\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'pymysql'"
     ]
    }
   ],
   "source": [
    "!python3 -m pip install pymysql\n",
    "!python3 -m pip install cryptography\n",
    "\n",
    "import pymysql\n",
    "\n",
    "timeout = 10\n",
    "connection = pymysql.connect(\n",
    "  charset=\"utf8mb4\",\n",
    "  connect_timeout=timeout,\n",
    "  cursorclass=pymysql.cursors.DictCursor,\n",
    "  db=\"defaultdb\",\n",
    "  host=\"mysql-eduardofarina-self-01.a.aivencloud.com\",\n",
    "  password=\"AVNS_EFCz8BR33pf0DTARSKL\",\n",
    "  read_timeout=timeout,\n",
    "  port=27648,\n",
    "  user=\"avnadmin\",\n",
    "  write_timeout=timeout,\n",
    ")\n",
    "  \n",
    "try:\n",
    "  cursor = connection.cursor()\n",
    "  cursor.execute(\"CREATE TABLE mytest (id INTEGER PRIMARY KEY)\")\n",
    "  cursor.execute(\"INSERT INTO mytest (id) VALUES (1), (2)\")\n",
    "  cursor.execute(\"SELECT * FROM mytest\")\n",
    "  print(cursor.fetchall())\n",
    "finally:\n",
    "  connection.close()\n",
    "  \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "python3 -m pip install psycopg2\n",
    "\n",
    "import psycopg2\n",
    "\n",
    "\n",
    "def main():\n",
    "    conn = psycopg2.connect('postgres://avnadmin:AVNS_HnesWmqFpCrMBE477T8@postgresql-eduardofarina-self-01.a.aivencloud.com:27648/defaultdb?sslmode=require')\n",
    "\n",
    "    query_sql = 'SELECT VERSION()'\n",
    "\n",
    "    cur = conn.cursor()\n",
    "    cur.execute(query_sql)\n",
    "\n",
    "    version = cur.fetchone()[0]\n",
    "    print(version)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
